apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  JwtSettings__Issuer: "EcommerceApi"
  JwtSettings__Audience: "EcommerceApiUsers"
  
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_API_URL: "https://api.ecommerce.example.com"
  
  Database__Provider: "SqlServer"
  Database__CommandTimeout: "30"
  Database__EnableRetryOnFailure: "true"
  Database__MaxRetryCount: "3"
