apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  
  JWT_SECRET_KEY: WW91clN1cGVyU2VjcmV0S2V5VGhhdElzQXRMZWFzdDMyQ2hhcmFjdGVyc0xvbmch
  
  DATABASE_CONNECTION_STRING: U2VydmVyPXNxbC1zZXJ2ZXI7RGF0YWJhc2U9RWNvbW1lcmNlRGI7VXNlciBJZD1zYTtQYXNzd29yZD1Zb3VyUGFzc3dvcmQxMjM7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVl
  
  SA_PASSWORD: WW91clBhc3N3b3JkMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-tls
  namespace: ecommerce
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...  # Base64 encoded private key
